$(message "GET INTO makefile")
SWE_solver:
	$(EXE) prog=SWE_solver out_dir=${OUT_DIR} dt=${DT} dmetric=${DMETRIC} n_x=${N_X} n_y=${N_Y} frame=${FRAME} height_max_ori=${HEIGHT_MAX_ORI} height_min_ori=${HEIGHT_MIN_ORI} gravity=${GRAVITY} fluid_density=${FLUID_DENSITY} rigid_body_density=${RIGID_BODY_DENSITY}
